import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'he' | 'en';

interface Translations {
  [key: string]: {
    he: string;
    en: string;
  };
}

const translations: Translations = {
  // Common
  'common.loading': { he: 'טוען...', en: 'Loading...' },
  'common.save': { he: 'שמירה', en: 'Save' },
  'common.cancel': { he: 'ביטול', en: 'Cancel' },
  'common.delete': { he: 'מחיקה', en: 'Delete' },
  'common.edit': { he: 'עריכה', en: 'Edit' },
  'common.create': { he: 'יצירה', en: 'Create' },
  'common.search': { he: 'חיפוש', en: 'Search' },
  'common.back': { he: 'חזרה', en: 'Back' },
  'common.minutes': { he: 'דקות', en: 'minutes' },
  'common.min': { he: 'ד׳', en: 'm' },
  'common.showAll': { he: 'הצגת הכל', en: 'Show All' },
  'common.error': { he: 'שגיאה', en: 'Error' },
  'common.success': { he: 'הצלחה', en: 'Success' },

  // Auth
  'auth.login': { he: 'התחברות', en: 'Login' },
  'auth.logout': { he: 'התנתקות', en: 'Logout' },
  'auth.signup': { he: 'הרשמה', en: 'Sign Up' },
  'auth.email': { he: 'אימייל', en: 'Email' },
  'auth.password': { he: 'סיסמה', en: 'Password' },
  'auth.fullName': { he: 'שם מלא', en: 'Full Name' },
  'auth.noAccount': { he: 'עדיין אין חשבון?', en: "Don't have an account?" },
  'auth.hasAccount': { he: 'יש כבר חשבון?', en: 'Already have an account?' },
  'auth.welcomeBack': { he: 'שמחים לראותך שוב', en: 'Welcome Back' },
  'auth.loginSubtitle': { he: 'התחברות להמשך הלמידה', en: 'Login to continue learning' },
  'auth.createAccount': { he: 'יצירת חשבון חדש', en: 'Create Account' },
  'auth.signupSubtitle': { he: 'הצטרפות למכללה שלנו', en: 'Join our college' },
  'auth.loginTitle': { he: 'התחברות', en: 'Login' },
  'auth.loginDesc': { he: 'יש להזין את פרטי ההתחברות כדי לגשת לחשבון', en: 'Enter your login details to access your account' },
  'auth.loginButton': { he: 'התחברות', en: 'Login' },
  'auth.loggingIn': { he: 'בתהליך התחברות...', en: 'Logging in...' },
  'auth.portalSubtitle': { he: 'פורטל הלמידה הדיגיטלי שלך', en: 'Your digital learning portal' },
  'auth.inviteOnly': { he: 'זהו פורטל בהזמנה בלבד. יש לפנות למנהל המערכת במקרה של צורך בגישה.', en: 'This is an invitation-only portal. Contact the administrator if you need access.' },
  'auth.loginFailed': { he: 'ההתחברות נכשלה', en: 'Login failed' },
  'auth.wrongCredentials': { he: 'אימייל או סיסמה שגויים. יש לנסות שוב.', en: 'Wrong email or password. Try again.' },
  'auth.welcomeMessage': { he: 'ברוכים הבאים!', en: 'Welcome!' },
  'auth.loginSuccess': { he: 'ההתחברות הצליחה.', en: 'Logged in successfully.' },
  'auth.unexpectedError': { he: 'אירעה שגיאה בלתי צפויה. יש לנסות שוב.', en: 'An unexpected error occurred. Try again.' },
  'auth.invalidEmail': { he: 'נא להזין כתובת אימייל תקינה', en: 'Please enter a valid email address' },
  'auth.passwordMinLength': { he: 'הסיסמה חייבת להכיל לפחות 6 תווים', en: 'Password must be at least 6 characters' },
  'auth.confirmPassword': { he: 'אימות סיסמה', en: 'Confirm password' },
  'auth.passwordsDontMatch': { he: 'הסיסמאות לא תואמות', en: 'Passwords do not match' },
  'auth.signingUp': { he: 'בתהליך הרשמה...', en: 'Signing up...' },
  'auth.signupFailed': { he: 'ההרשמה נכשלה', en: 'Sign up failed' },
  'auth.signupSuccess': { he: 'החשבון נוצר בהצלחה.', en: 'Account created successfully.' },

  // Navigation
  'nav.dashboard': { he: 'לוח בקרה', en: 'Dashboard' },
  'nav.courses': { he: 'קורסים', en: 'Courses' },
  'nav.studyRooms': { he: 'חדרי לימוד', en: 'Study Rooms' },
  'nav.calendar': { he: 'לוח שנה', en: 'Calendar' },
  'nav.announcements': { he: 'הודעות', en: 'Announcements' },
  'nav.profile': { he: 'פרופיל', en: 'Profile' },
  'nav.manageUsers': { he: 'ניהול משתמשים', en: 'Manage Users' },
  'nav.settings': { he: 'הגדרות', en: 'Settings' },
  'nav.skillsLibrary': { he: 'ספריית סקילים', en: 'Skills Library' },
  'nav.manageSkills': { he: 'ניהול סקילים', en: 'Manage Skills' },

  // Skills Library
  'skills.title': { he: 'ספריית סקילים', en: 'Skills Library' },
  'skills.search': { he: 'חיפוש סקילים...', en: 'Search skills...' },
  'skills.submit': { he: 'שליחת סקיל', en: 'Submit Skill' },
  'skills.submitNew': { he: 'שליחת סקיל חדש', en: 'Submit New Skill' },
  'skills.download': { he: 'הורדה', en: 'Download' },
  'skills.rating': { he: 'דירוג', en: 'Rating' },
  'skills.downloads': { he: 'הורדות', en: 'Downloads' },
  'skills.category': { he: 'קטגוריה', en: 'Category' },
  'skills.tags': { he: 'תגיות', en: 'Tags' },
  'skills.name': { he: 'שם', en: 'Name' },
  'skills.description': { he: 'תיאור', en: 'Description' },
  'skills.longDescription': { he: 'תיאור מפורט', en: 'Detailed Description' },
  'skills.triggerPattern': { he: 'תבנית הפעלה', en: 'Trigger Pattern' },
  'skills.fileContent': { he: 'תוכן הקובץ', en: 'File Content' },
  'skills.status.draft': { he: 'טיוטה', en: 'Draft' },
  'skills.status.submitted': { he: 'בבדיקה', en: 'Under Review' },
  'skills.status.scanning': { he: 'בסריקה', en: 'Scanning' },
  'skills.status.approved': { he: 'מאושר', en: 'Approved' },
  'skills.status.rejected': { he: 'נדחה', en: 'Rejected' },
  'skills.uploadFile': { he: 'העלאת קובץ', en: 'Upload File' },
  'skills.featured': { he: 'מומלץ', en: 'Featured' },
  'skills.mySkills': { he: 'הסקילים שלי', en: 'My Skills' },
  'skills.allSkills': { he: 'כל הסקילים', en: 'All Skills' },
  'skills.noResults': { he: 'לא נמצאו סקילים', en: 'No skills found' },
  'skills.version': { he: 'גרסה', en: 'Version' },
  'skills.approve': { he: 'אישור', en: 'Approve' },
  'skills.reject': { he: 'דחייה', en: 'Reject' },
  'skills.scanPassed': { he: 'עבר סריקה', en: 'Scan Passed' },
  'skills.scanFailed': { he: 'נכשל בסריקה', en: 'Scan Failed' },
  'skills.scanPending': { he: 'ממתין לסריקה', en: 'Scan Pending' },
  'skills.author': { he: 'מחבר/ת', en: 'Author' },
  'skills.versions': { he: 'גרסאות', en: 'Versions' },
  'skills.reviews': { he: 'ביקורות', en: 'Reviews' },
  'skills.writeReview': { he: 'כתיבת ביקורת', en: 'Write a review' },
  'skills.rateSkill': { he: 'דירוג הסקיל', en: 'Rate this skill' },
  'skills.submitReview': { he: 'שליחת ביקורת', en: 'Submit Review' },
  'skills.deleteConfirm': { he: 'האם למחוק את הסקיל?', en: 'Are you sure you want to delete this skill?' },
  'skills.rejectNotes': { he: 'הערות דחייה', en: 'Rejection notes' },
  'skills.approveConfirm': { he: 'לאשר את הסקיל?', en: 'Approve this skill?' },
  'skills.contentPreview': { he: 'תצוגת תוכן', en: 'Content Preview' },
  'skills.scanResults': { he: 'תוצאות סריקה', en: 'Scan Results' },
  'skills.sortNewest': { he: 'חדש ביותר', en: 'Newest' },
  'skills.sortPopular': { he: 'פופולרי', en: 'Most Popular' },
  'skills.sortTopRated': { he: 'דירוג גבוה', en: 'Top Rated' },
  'skills.categories.general': { he: 'כללי', en: 'General' },
  'skills.categories.coding': { he: 'קוד', en: 'Coding' },
  'skills.categories.devops': { he: 'DevOps', en: 'DevOps' },
  'skills.categories.testing': { he: 'בדיקות', en: 'Testing' },
  'skills.categories.documentation': { he: 'תיעוד', en: 'Documentation' },
  'skills.categories.security': { he: 'אבטחה', en: 'Security' },
  'skills.categories.design': { he: 'עיצוב', en: 'Design' },
  'skills.categories.data': { he: 'נתונים', en: 'Data' },
  'skills.uploadOrPaste': { he: 'העלאת קובץ .md או הדבקת תוכן', en: 'Upload .md file or paste content' },
  'skills.dragDrop': { he: 'יש לגרור קובץ לכאן', en: 'Drag file here' },
  'skills.submitting': { he: 'בשליחה...', en: 'Submitting...' },
  'skills.submitted': { he: 'הסקיל נשלח בהצלחה!', en: 'Skill submitted successfully!' },
  'skills.submitError': { he: 'שגיאה בשליחת הסקיל', en: 'Error submitting skill' },
  'skills.edit': { he: 'עריכה', en: 'Edit' },
  'skills.editSkill': { he: 'עריכת סקיל', en: 'Edit Skill' },
  'skills.icon': { he: 'אייקון', en: 'Icon' },
  'skills.rescan': { he: 'סריקה מחדש', en: 'Rescan' },
  'skills.scanFailedBadge': { he: 'סריקה נכשלה', en: 'Scan Failed' },
  'skills.viewContent': { he: 'צפייה בתוכן', en: 'View Content' },
  'skills.rejectionReason': { he: 'סיבת הדחייה', en: 'Rejection Reason' },

  // Dashboard
  'dashboard.goodMorning': { he: 'בוקר טוב', en: 'Good morning' },
  'dashboard.goodAfternoon': { he: 'צהריים טובים', en: 'Good afternoon' },
  'dashboard.goodEvening': { he: 'ערב טוב', en: 'Good evening' },
  'dashboard.welcomeSubtitle': { he: 'הנה מה שקורה בלמידה שלך היום.', en: "Here's what's happening with your learning today." },
  'dashboard.allCourses': { he: 'לכל הקורסים', en: 'All Courses' },
  'dashboard.enrolledCourses': { he: 'קורסים רשומים', en: 'Enrolled Courses' },
  'dashboard.completedLessons': { he: 'שיעורים הושלמו', en: 'Completed Lessons' },
  'dashboard.upcomingEvents': { he: 'אירועים קרובים', en: 'Upcoming Events' },
  'dashboard.activeRooms': { he: 'חדרים פעילים', en: 'Active Rooms' },
  'dashboard.totalUsers': { he: 'סה״כ משתמשים', en: 'Total Users' },
  'dashboard.totalCourses': { he: 'סה״כ קורסים', en: 'Total Courses' },
  'dashboard.totalEnrollments': { he: 'סה״כ הרשמות', en: 'Total Enrollments' },
  'dashboard.announcements': { he: 'הודעות', en: 'Announcements' },
  'dashboard.recentCourses': { he: 'קורסים אחרונים', en: 'Recent Courses' },
  'dashboard.latestAddedCourses': { he: 'הקורסים האחרונים שנוספו', en: 'Latest courses added' },
  'dashboard.noCourses': { he: 'אין קורסים', en: 'No courses' },
  'dashboard.createCourse': { he: 'יצירת קורס', en: 'Create Course' },
  'dashboard.myCourses': { he: 'הקורסים שלי', en: 'My Courses' },
  'dashboard.continueWhere': { he: 'להמשיך מהמקום האחרון', en: 'Continue where you left off' },
  'dashboard.notEnrolled': { he: 'עדיין אין רישום לקורסים', en: 'Not enrolled in any courses yet' },
  'dashboard.browseAvailable': { he: 'לעיין בקורסים הזמינים', en: 'Browse available courses' },
  'dashboard.dontMiss': { he: 'לא לפספס', en: "Don't miss" },
  'dashboard.showCalendar': { he: 'הצגת לוח שנה', en: 'Show Calendar' },
  'dashboard.noUpcomingEvents': { he: 'אין אירועים קרובים', en: 'No upcoming events' },
  'dashboard.quickActions': { he: 'פעולות מהירות', en: 'Quick Actions' },
  'dashboard.joinStudyRoom': { he: 'הצטרפות לחדר לימוד', en: 'Join Study Room' },
  'dashboard.showCalendarAction': { he: 'הצגת לוח שנה', en: 'Show Calendar' },
  'dashboard.latestUpdates': { he: 'עדכונים אחרונים', en: 'Latest Updates' },

  // Courses
  'courses.title': { he: 'קורסים', en: 'Courses' },
  'courses.subtitle': { he: 'חקירה וניהול של מסע הלמידה שלך', en: 'Explore and manage your learning journey' },
  'courses.createCourse': { he: 'יצירת קורס', en: 'Create Course' },
  'courses.searchPlaceholder': { he: 'חיפוש קורסים...', en: 'Search courses...' },
  'courses.myCourses': { he: 'הקורסים שלי', en: 'My Courses' },
  'courses.browseCourses': { he: 'עיון בכל הקורסים', en: 'Browse All Courses' },
  'courses.noEnrolled': { he: 'אין קורסים רשומים', en: 'No enrolled courses' },
  'courses.noEnrolledDesc': { he: 'להתחיל ללמוד באמצעות הרשמה לקורס', en: 'Start learning by enrolling in a course' },
  'courses.browseButton': { he: 'עיון בקורסים', en: 'Browse Courses' },
  'courses.noCourses': { he: 'אין קורסים זמינים', en: 'No courses available' },
  'courses.noCoursesDesc': { he: 'יש לבדוק שוב מאוחר יותר לקורסים חדשים', en: 'Check back later for new courses' },
  'courses.progress': { he: 'התקדמות', en: 'Progress' },
  'courses.modules': { he: 'מודולים', en: 'modules' },
  'courses.enrollNow': { he: 'להירשם עכשיו', en: 'Enroll Now' },
  'courses.continueLearning': { he: 'להמשיך ללמוד', en: 'Continue Learning' },
  'courses.noDescription': { he: 'אין תיאור', en: 'No description' },
  'courses.instructor': { he: 'מרצה', en: 'Instructor' },
  'courses.noInstructor': { he: 'ללא מרצה', en: 'No instructor' },
  'courses.draft': { he: 'טיוטה', en: 'Draft' },
  'courses.publish': { he: 'פרסום', en: 'Publish' },
  'courses.unpublish': { he: 'ביטול פרסום', en: 'Unpublish' },
  'courses.editCourse': { he: 'עריכת קורס', en: 'Edit Course' },
  'courses.deleteCourse': { he: 'מחיקת קורס', en: 'Delete Course' },
  'courses.deleteConfirm': { he: 'האם למחוק את הקורס?', en: 'Are you sure you want to delete this course?' },
  'courses.deleteConfirmDesc': { he: 'פעולה זו לא ניתנת לביטול. כל המודולים והשיעורים יימחקו.', en: 'This action cannot be undone. All modules and lessons will be deleted.' },
  'courses.published': { he: 'הקורס פורסם', en: 'Course published' },
  'courses.unpublished': { he: 'הקורס הוסר מפרסום', en: 'Course unpublished' },
  'courses.deleted': { he: 'הקורס נמחק', en: 'Course deleted' },
  'courses.purchaseCourse': { he: 'רכישת קורס', en: 'Purchase Course' },
  'courses.paidCourse': { he: 'קורס בתשלום', en: 'Paid Course' },
  'courses.contactAdmin': { he: 'יש לפנות למנהל המערכת להרשמה לקורס זה', en: 'Please contact the system administrator to enroll in this course' },
  'courses.minutes': { he: 'דקות', en: 'minutes' },
  'courses.hours': { he: 'שעות', en: 'hours' },

  // Course Detail
  'courseDetail.complete': { he: '% הושלם', en: '% complete' },
  'courseDetail.markComplete': { he: 'סימון כהושלם', en: 'Mark as Complete' },
  'courseDetail.autoAdvanceLabel': { he: 'מעבר אוטומטי', en: 'Auto-advance' },
  'courseDetail.autoAdvanceTooltip': { he: 'בסיום השיעור, השיעור יסומן אוטומטית כהושלם והשיעור הבא יתחיל להתנגן.', en: 'When a lesson ends, it is automatically marked complete and the next lesson starts playing.' },
  'courseDetail.completed': { he: 'הושלם', en: 'Completed' },
  'courseDetail.lessonUnmarked': { he: 'השיעור סומן כלא הושלם', en: 'Lesson unmarked' },
  'courseDetail.lessonUnmarkedDesc': { he: 'השיעור סומן כלא הושלם', en: 'The lesson has been marked as incomplete' },
  'courseDetail.lessonCompleted': { he: 'השיעור הושלם!', en: 'Lesson completed!' },
  'courseDetail.lessonCompletedDesc': { he: 'עבודה מצוינת, כל הכבוד!', en: 'Great job! Keep up the good work.' },
  'courseDetail.downloadResources': { he: 'הורדת משאבים', en: 'Download Resources' },
  'courseDetail.myNotes': { he: 'ההערות שלי', en: 'My Notes' },
  'courseDetail.addNotePlaceholder': { he: 'הוספת הערה לשיעור זה...', en: 'Add a note for this lesson...' },
  'courseDetail.saveNote': { he: 'שמירת הערה', en: 'Save Note' },
  'courseDetail.noteSaved': { he: 'ההערה נשמרה', en: 'Note saved' },
  'courseDetail.noteSavedDesc': { he: 'ההערה נוספה לשיעור זה.', en: 'Your note has been added to this lesson.' },
  'courseDetail.courseContent': { he: 'תוכן הקורס', en: 'Course Content' },
  'courseDetail.lessons': { he: 'שיעורים', en: 'lessons' },
  'courseDetail.courseNotFound': { he: 'הקורס לא נמצא', en: 'Course not found' },
  'courseDetail.backToCourses': { he: 'חזרה לקורסים', en: 'Back to Courses' },
  'courseDetail.accessDenied': { he: 'אין גישה לקורס זה', en: 'Access Denied' },
  'courseDetail.accessDeniedDesc': { he: 'אין רישום לקורס זה. יש לפנות למנהל המערכת או להירשם לקורס כדי לקבל גישה.', en: 'You are not enrolled in this course. Contact the administrator or enroll to get access.' },
  'courseDetail.enrollNow': { he: 'להירשם עכשיו', en: 'Enroll Now' },
  'courseDetail.description': { he: 'תיאור השיעור', en: 'Lesson Description' },
  'courseDetail.usefulResources': { he: 'משאבים שימושיים', en: 'Useful Resources' },
  'courseDetail.noDescription': { he: 'אין תיאור לשיעור זה', en: 'No description for this lesson' },
  'courseDetail.noResources': { he: 'אין משאבים להורדה', en: 'No resources available' },
  'courseDetail.resource': { he: 'משאב', en: 'Resource' },
  'courseDetail.downloadFile': { he: 'הורדת קובץ', en: 'Download File' },
  'courseDetail.openInNewTab': { he: 'פתיחה בחלון חדש', en: 'Open in New Tab' },
  'courseDetail.favorites': { he: 'מועדפים', en: 'Favorites' },
  'courseDetail.watchLater': { he: 'צפייה מאוחרת', en: 'Watch Later' },
  'courseDetail.addToFavorites': { he: 'הוספה למועדפים', en: 'Add to Favorites' },
  'courseDetail.removeFromFavorites': { he: 'הסרה ממועדפים', en: 'Remove from Favorites' },
  'courseDetail.addToWatchLater': { he: 'צפייה מאוחר יותר', en: 'Watch Later' },
  'courseDetail.removeFromWatchLater': { he: 'הסרה מצפייה מאוחרת', en: 'Remove from Watch Later' },
  'bookmarks.favoritesTitle': { he: 'השיעורים המועדפים שלי', en: 'My Favorite Lessons' },
  'bookmarks.watchLaterTitle': { he: 'רשימת צפייה מאוחרת', en: 'Watch Later List' },
  'bookmarks.noFavorites': { he: 'עדיין לא נוספו שיעורים למועדפים', en: 'No favorite lessons yet' },
  'bookmarks.noFavoritesDesc': { he: 'יש ללחוץ על הכוכב בעמוד השיעור כדי להוסיף שיעורים למועדפים', en: 'Click the star on a lesson page to add it to your favorites' },
  'bookmarks.noWatchLater': { he: 'אין שיעורים ברשימת הצפייה', en: 'No watch later lessons yet' },
  'bookmarks.noWatchLaterDesc': { he: 'יש ללחוץ על השעון בעמוד השיעור כדי להוסיף שיעורים לצפייה מאוחרת', en: 'Click the clock on a lesson page to add it to your watch later list' },

  // Create Course
  'createCourse.title': { he: 'יצירת קורס חדש', en: 'Create New Course' },
  'createCourse.subtitle': { he: 'הוספת קורס חדש עם מודולים ושיעורים', en: 'Add a new course with modules and lessons' },
  'createCourse.courseDetails': { he: 'פרטי הקורס', en: 'Course Details' },
  'createCourse.courseName': { he: 'שם הקורס', en: 'Course Name' },
  'createCourse.courseNamePlaceholder': { he: 'לדוגמה: מבוא לבינה מלאכותית', en: 'e.g., Introduction to AI' },
  'createCourse.description': { he: 'תיאור הקורס', en: 'Course Description' },
  'createCourse.descriptionPlaceholder': { he: 'תיאור קצר של הקורס...', en: 'Describe the course briefly...' },
  'createCourse.thumbnail': { he: 'תמונת קורס', en: 'Course Thumbnail' },
  'createCourse.thumbnailUrl': { he: 'קישור לתמונת קורס', en: 'Course Thumbnail URL' },
  'createCourse.uploadImage': { he: 'העלאת תמונה', en: 'Upload Image' },
  'createCourse.orEnterUrl': { he: 'או הזנת קישור', en: 'or enter URL' },
  'createCourse.uploading': { he: 'בהעלאה...', en: 'Uploading...' },
  'createCourse.paymentUrl': { he: 'קישור לדף תשלום (אופציונלי)', en: 'Payment URL (optional)' },
  'createCourse.paymentUrlPlaceholder': { he: 'לדוגמה: https://payment.example.com/course', en: 'e.g., https://payment.example.com/course' },
  'createCourse.publishNow': { he: 'פרסום הקורס מיד', en: 'Publish course immediately' },
  'createCourse.modulesAndLessons': { he: 'מודולים ושיעורים', en: 'Modules and Lessons' },
  'createCourse.addModule': { he: 'הוספת מודול', en: 'Add Module' },
  'createCourse.module': { he: 'מודול', en: 'Module' },
  'createCourse.moduleName': { he: 'שם המודול', en: 'Module Name' },
  'createCourse.moduleNamePlaceholder': { he: 'לדוגמה: יסודות', en: 'e.g., Basics' },
  'createCourse.moduleDescription': { he: 'תיאור המודול', en: 'Module Description' },
  'createCourse.lessons': { he: 'שיעורים', en: 'Lessons' },
  'createCourse.addLesson': { he: 'הוספת שיעור', en: 'Add Lesson' },
  'createCourse.lesson': { he: 'שיעור', en: 'Lesson' },
  'createCourse.lessonName': { he: 'שם השיעור', en: 'Lesson Name' },
  'createCourse.videoUrl': { he: 'קישור לסרטון (YouTube/Vimeo)', en: 'Video URL (YouTube/Vimeo)' },
  'createCourse.contentText': { he: 'תוכן טקסטואלי (אופציונלי)', en: 'Text content (optional)' },
  'createCourse.durationMinutes': { he: 'דקות', en: 'Minutes' },
  'createCourse.creating': { he: 'בתהליך יצירה...', en: 'Creating...' },
  'createCourse.create': { he: 'יצירת קורס', en: 'Create Course' },
  'createCourse.success': { he: 'הקורס נוצר בהצלחה!', en: 'Course created successfully!' },
  'createCourse.loginRequired': { he: 'יש להתחבר כדי ליצור קורס', en: 'Login required to create a course' },
  'createCourse.nameRequired': { he: 'יש להזין שם לקורס', en: 'Course name is required' },
  'createCourse.moduleTitleRequired': { he: 'יש להזין שם למודול שמכיל שיעורים', en: 'Module with lessons must have a title' },
  'createCourse.lessonTitleRequired': { he: 'יש להזין שם לכל השיעורים', en: 'All lessons must have a title' },
  'createCourse.selectInstructor': { he: 'בחירת מרצים', en: 'Select Instructors' },
  'createCourse.selectInstructorPlaceholder': { he: 'בחירת מרצים לקורס...', en: 'Select course instructors...' },
  'createCourse.instructorsSelected': { he: 'מרצים נבחרו', en: 'instructors selected' },
  'createCourse.noInstructors': { he: 'אין מרצים זמינים', en: 'No instructors available' },
  'createCourse.lessonTypeVideo': { he: 'סרטון', en: 'Video' },
  'createCourse.lessonTypeFile': { he: 'קובץ', en: 'File' },
  'createCourse.lessonTypeExam': { he: 'מבחן', en: 'Exam' },
  'createCourse.uploadFile': { he: 'העלאת קובץ', en: 'Upload File' },
  'createCourse.viewFile': { he: 'צפייה בקובץ', en: 'View File' },
  'createCourse.fileUrlPlaceholder': { he: 'או הזנת קישור לקובץ', en: 'Or enter file URL' },
  'createCourse.selectExam': { he: 'בחירת מבחן', en: 'Select Exam' },
  'createCourse.noExamsAvailable': { he: 'אין מבחנים זמינים. יש ליצור מבחנים תחילה.', en: 'No exams available. Create exams first.' },

  // Lesson Form
  'lessonForm.embedSite': { he: 'הטמעת אתר', en: 'Embed Site' },
  'lessonForm.embedUrlPlaceholder': { he: 'קישור להטמעה', en: 'Embed URL' },
  'lessonForm.embedUrlHint': { he: 'יש להזין קישור לאתר שתומך בהטמעה', en: 'Enter a URL that supports embedding' },
  'lessonForm.lessonDescription': { he: 'תיאור השיעור', en: 'Lesson Description' },
  'lessonForm.lessonDescriptionPlaceholder': { he: 'יש להזין תיאור מפורט לשיעור...', en: 'Enter a detailed lesson description...' },
  'lessonForm.usefulResources': { he: 'משאבים שימושיים', en: 'Useful Resources' },
  'lessonForm.uploadResources': { he: 'העלאת משאב', en: 'Upload' },
  'lessonForm.noResourcesYet': { he: 'אין משאבים עדיין', en: 'No resources yet' },
  'lessonForm.resource': { he: 'משאב', en: 'Resource' },
  'lessonForm.resourceName': { he: 'שם המשאב (אופציונלי)', en: 'Resource name (optional)' },
  'lessonForm.generateSummary': { he: 'יצירת סיכום', en: 'Generate Summary' },
  'lessonForm.downloadingVideo': { he: 'בהורדת סרטון...', en: 'Downloading video...' },
  'lessonForm.transcribing': { he: 'בתמלול...', en: 'Transcribing...' },
  'lessonForm.summarizing': { he: 'בסיכום...', en: 'Summarizing...' },
  'lessonForm.summaryReady': { he: 'הסיכום מוכן!', en: 'Summary generated!' },
  'lessonForm.summaryError': { he: 'שגיאה ביצירת הסיכום', en: 'Failed to generate summary' },
  'lessonForm.summaryLanguage': { he: 'שפת הסיכום', en: 'Summary language' },
  'lessonForm.hebrew': { he: 'עברית', en: 'Hebrew' },
  'lessonForm.english': { he: 'אנגלית', en: 'English' },
  'lessonForm.hideFromStudents': { he: 'הסתרה מתלמידים', en: 'Hide from students' },
  'lessonForm.hiddenFromStudents': { he: 'מוסתר מתלמידים', en: 'Hidden from students' },

  // Exams
  'exams.title': { he: 'מבחנים', en: 'Exams' },
  'exams.addExam': { he: 'הוספת מבחן', en: 'Add Exam' },
  'exams.createExam': { he: 'יצירת מבחן', en: 'Create Exam' },
  'exams.editExam': { he: 'עריכת מבחן', en: 'Edit Exam' },
  'exams.examTitle': { he: 'שם המבחן', en: 'Exam Title' },
  'exams.examTitlePlaceholder': { he: 'לדוגמה: מבחן סיום', en: 'e.g., Final Exam' },
  'exams.passingScore': { he: 'ציון עובר (%)', en: 'Passing Score (%)' },
  'exams.timeLimit': { he: 'מגבלת זמן (דקות)', en: 'Time Limit (minutes)' },
  'exams.timeLimitPlaceholder': { he: 'יש להשאיר ריק ללא הגבלה', en: 'Leave empty for no limit' },
  'exams.publishExam': { he: 'פרסום מבחן', en: 'Publish Exam' },
  'exams.description': { he: 'תיאור', en: 'Description' },
  'exams.descriptionPlaceholder': { he: 'תיאור קצר של המבחן...', en: 'Brief description of the exam...' },
  'exams.questions': { he: 'שאלות', en: 'Questions' },
  'exams.addQuestion': { he: 'הוספת שאלה', en: 'Add Question' },
  'exams.question': { he: 'שאלה', en: 'Question' },
  'exams.questionTextPlaceholder': { he: 'יש להזין את טקסט השאלה...', en: 'Enter question text...' },
  'exams.option': { he: 'אפשרות', en: 'Option' },
  'exams.correctAnswer': { he: 'תשובה נכונה', en: 'Correct Answer' },
  'exams.correctAnswerPlaceholder': { he: 'יש להזין את התשובה הנכונה', en: 'Enter the correct answer' },
  'exams.points': { he: 'נקודות', en: 'Points' },
  'exams.titleRequired': { he: 'יש להזין שם למבחן', en: 'Exam title is required' },
  'exams.created': { he: 'המבחן נוצר בהצלחה', en: 'Exam created successfully' },
  'exams.updated': { he: 'המבחן עודכן בהצלחה', en: 'Exam updated successfully' },
  'exams.deleted': { he: 'המבחן נמחק', en: 'Exam deleted' },
  'exams.deleteConfirm': { he: 'האם למחוק את המבחן?', en: 'Are you sure you want to delete this exam?' },
  'exams.noExams': { he: 'אין מבחנים לקורס זה', en: 'No exams for this course' },
  'exams.options': { he: 'אפשרויות', en: 'Options' },
  'exams.addOption': { he: 'הוספת אפשרות', en: 'Add Option' },
  'exams.correct': { he: 'נכון', en: 'Correct' },
  'exams.addImage': { he: 'הוספת תמונה', en: 'Add Image' },
  'exams.explanationPlaceholder': { he: 'הסבר לתשובה זו (יופיע אחרי מענה)...', en: 'Explanation for this answer (shown after answering)...' },
  'exams.generalExplanation': { he: 'הסבר כללי לשאלה', en: 'General explanation for the question' },
  'exams.generalExplanationPlaceholder': { he: 'הסבר שיופיע אחרי מענה על השאלה...', en: 'Explanation shown after answering the question...' },

  // Study Rooms
  'studyRooms.title': { he: 'חדרי לימוד', en: 'Study Rooms' },
  'studyRooms.subtitle': { he: 'יצירה או הצטרפות לפגישות לימוד וירטואליות עם עמיתים', en: 'Create or join virtual study meetings with your peers' },
  'studyRooms.createRoom': { he: 'יצירת חדר', en: 'Create Room' },
  'studyRooms.createStudyRoom': { he: 'יצירת חדר לימוד', en: 'Create Study Room' },
  'studyRooms.createRoomDesc': { he: 'הקמת חדר לימוד וירטואלי חדש לשיתוף פעולה', en: 'Set up a new virtual study room for collaboration' },
  'studyRooms.leaveRoom': { he: 'יציאה מהחדר', en: 'Leave Room' },
  'studyRooms.enterName': { he: 'הזנת שם', en: 'Enter your name' },
  'studyRooms.namePlaceholder': { he: 'השם שלך', en: 'Your name' },
  'studyRooms.joinRoom': { he: 'הצטרפות לחדר', en: 'Join Room' },
  'studyRooms.activeRooms': { he: 'חדרים פעילים', en: 'Active Rooms' },
  'studyRooms.noRooms': { he: 'אין חדרי לימוד פעילים כרגע', en: 'No active study rooms yet' },
  'studyRooms.noRoomsDesc': {
    he: 'חדרי לימוד הם מקום ללמוד יחד עם חברי הקהילה — לפתור תרגילים, להתייעץ על פרויקטים או פשוט ללמוד באווירה משותפת. אפשר ליצור את החדר הראשון ולהזמין אחרים להצטרף.',
    en: 'Study rooms are a place to learn together with other members — solve exercises, discuss projects, or just study in a shared atmosphere. Create the first room and invite others to join.',
  },
  'studyRooms.participants': { he: 'משתתפים', en: 'participants' },
  'studyRooms.host': { he: 'מארח/ת', en: 'Host' },
  'studyRooms.join': { he: 'הצטרפות', en: 'Join' },
  'studyRooms.roomName': { he: 'שם החדר', en: 'Room Name' },
  'studyRooms.roomNamePlaceholder': { he: 'לדוגמה: קבוצת לימוד AI', en: 'e.g., AI Study Group' },
  'studyRooms.roomDescription': { he: 'תיאור (אופציונלי)', en: 'Description (optional)' },
  'studyRooms.descriptionPlaceholder': { he: 'על מה תלמדו?', en: 'What will you study?' },
  'studyRooms.category': { he: 'קטגוריה', en: 'Category' },
  'studyRooms.maxParticipants': { he: 'מספר משתתפים מקסימלי', en: 'Maximum Participants' },
  'studyRooms.lockedRoom': { he: 'חדר נעול', en: 'Locked Room' },
  'studyRooms.lockedRoomDesc': { he: 'רק אנשים שהוזמנו יוכלו להצטרף', en: 'Only invited people can join' },
  'studyRooms.creating': { he: 'בתהליך יצירה...', en: 'Creating...' },
  'studyRooms.roomCreated': { he: 'החדר נוצר!', en: 'Room created!' },
  'studyRooms.roomCreatedDesc': { he: 'חדר הלימוד מוכן. ניתן להצטרף אליו עכשיו.', en: 'Your study room is ready. You can join it now.' },
  'studyRooms.roomDeleted': { he: 'החדר נמחק', en: 'Room deleted' },
  'studyRooms.roomDeletedDesc': { he: 'חדר הלימוד הוסר.', en: 'The study room has been removed.' },
  'studyRooms.roomLocked': { he: 'החדר נעול', en: 'Room is locked' },
  'studyRooms.roomLockedDesc': { he: 'רק מי שהוזמן יכול להצטרף לחדר זה.', en: 'Only invited people can join this room.' },
  'studyRooms.deleteRoom': { he: 'למחוק את חדר הלימוד?', en: 'Delete study room?' },
  'studyRooms.deleteRoomDesc': { he: 'פעולה זו תמחק לצמיתות את החדר ותסיר את כל המשתתפים.', en: 'This action will permanently delete the room and remove all participants.' },
  'studyRooms.locked': { he: 'נעול', en: 'Locked' },
  'studyRooms.open': { he: 'פתוח', en: 'Open' },
  'studyRooms.builtInVideo': { he: 'שיחות וידאו מובנות', en: 'Built-in Video Calls' },
  'studyRooms.builtInVideoDesc': { he: 'חדרי הלימוד משתמשים בטכנולוגיית WebRTC לשיחות וידאו ישירות בתוך האפליקציה. יש ללחוץ על "הצטרפות לחדר" כדי להתחיל לשתף פעולה עם חברי הכיתה.', en: 'Study rooms use WebRTC technology for direct video calls within the app. Click "Join Room" to start collaborating with your classmates.' },
  'studyRooms.categoryGeneral': { he: 'כללי', en: 'General' },
  'studyRooms.categoryStudy': { he: 'לימודים', en: 'Study' },
  'studyRooms.categoryProject': { he: 'פרויקט', en: 'Project' },
  'studyRooms.categoryDiscussion': { he: 'דיון', en: 'Discussion' },
  'studyRooms.liveRoom': { he: 'שידור לייב', en: 'Live Broadcast' },
  'studyRooms.liveRoomDesc': { he: 'החדר ישודר בזמן אמת', en: 'The room will be broadcast in real-time' },
  'studyRooms.recordRoom': { he: 'הקלטת החדר', en: 'Record Room' },
  'studyRooms.recordRoomDesc': { he: 'הפגישה תוקלט לצפייה מאוחרת', en: 'The meeting will be recorded for later viewing' },
  'studyRooms.live': { he: 'לייב', en: 'LIVE' },
  'studyRooms.recording': { he: 'מוקלט', en: 'Recording' },

  // Calendar
  'calendar.title': { he: 'לוח אירועים', en: 'Event Calendar' },
  'calendar.subtitle': { he: 'צפייה ואישור הגעה לאירועים קרובים', en: 'View and RSVP for upcoming events' },
  'calendar.createEvent': { he: 'יצירת אירוע', en: 'Create Event' },
  'calendar.newEvent': { he: 'יצירת אירוע', en: 'Create Event' },
  'calendar.newEventDesc': { he: 'הוספת אירוע חדש ללוח השנה', en: 'Add a new event to the calendar' },
  'calendar.upcomingEvents': { he: 'כל האירועים הקרובים', en: 'All Upcoming Events' },
  'calendar.noEvents': { he: 'אין אירועים מתוכננים', en: 'No events scheduled' },
  'calendar.noEventsDesc': { he: 'ניתן לבחור תאריך או ליצור אירוע חדש', en: 'Select a date or create a new event' },
  'calendar.eventTitle': { he: 'שם האירוע', en: 'Event Name' },
  'calendar.eventTitlePlaceholder': { he: 'לדוגמה: הרצאת אורח', en: 'e.g., Guest Lecture' },
  'calendar.eventDescription': { he: 'תיאור', en: 'Description' },
  'calendar.descriptionPlaceholder': { he: 'פרטי האירוע...', en: 'Event details...' },
  'calendar.startTime': { he: 'שעת התחלה', en: 'Start Time' },
  'calendar.endTime': { he: 'שעת סיום', en: 'End Time' },
  'calendar.location': { he: 'מיקום (אופציונלי)', en: 'Location (optional)' },
  'calendar.locationPlaceholder': { he: 'לדוגמה: חדר 101', en: 'e.g., Room 101' },
  'calendar.meetingUrl': { he: 'קישור לפגישה (אופציונלי)', en: 'Meeting URL (optional)' },
  'calendar.rsvp': { he: 'אגיע', en: 'I\'m attending' },
  'calendar.attending': { he: 'נרשמתי', en: 'Attending' },
  'calendar.notAttending': { he: 'לא אגיע', en: 'Not Attending' },
  'calendar.participants': { he: 'משתתפים', en: 'participants' },
  'calendar.joinMeeting': { he: 'הצטרפות', en: 'Join' },
  'calendar.creating': { he: 'בתהליך יצירה...', en: 'Creating...' },
  'calendar.eventCreated': { he: 'האירוע נוצר!', en: 'Event created!' },
  'calendar.eventCreatedDesc': { he: 'האירוע נוסף ללוח השנה.', en: 'The event has been added to the calendar.' },
  'calendar.registered': { he: 'נרשמת בהצלחה!', en: 'Successfully registered!' },
  'calendar.registeredDesc': { he: 'האישור התקבל.', en: 'Your RSVP has been received.' },
  'calendar.unregistered': { he: 'האישור בוטל', en: 'RSVP cancelled' },
  'calendar.today': { he: 'היום', en: 'Today' },
  'calendar.nextMonth': { he: 'חודש הבא', en: 'Next month' },
  'calendar.prevMonth': { he: 'חודש קודם', en: 'Previous month' },
  'calendar.events': { he: 'אירועים', en: 'events' },
  'calendar.noUpcoming': { he: 'אין אירועים קרובים', en: 'No upcoming events' },
  'calendar.sync': { he: 'סנכרון', en: 'Sync' },
  'calendar.syncing': { he: 'בתהליך סנכרון...', en: 'Syncing...' },

  // Announcements
  'announcements.title': { he: 'הודעות', en: 'Announcements' },
  'announcements.subtitle': { he: 'עדכונים על כל החדשות האחרונות', en: 'Stay updated with the latest news and updates' },
  'announcements.newAnnouncement': { he: 'הודעה חדשה', en: 'New Announcement' },
  'announcements.newAnnouncementDesc': { he: 'יצירת הודעה שתהיה גלויה לכל המשתמשים', en: 'Create an announcement visible to all users' },
  'announcements.publishAnnouncement': { he: 'פרסום הודעה', en: 'Publish Announcement' },
  'announcements.noAnnouncements': { he: 'אין הודעות עדיין', en: 'No announcements yet' },
  'announcements.noAnnouncementsDesc': { he: 'יש לבדוק שוב מאוחר יותר לעדכונים מהמכללה', en: 'Check back later for updates from the college' },
  'announcements.pinned': { he: 'מוצמד', en: 'Pinned' },
  'announcements.announcementTitle': { he: 'כותרת', en: 'Title' },
  'announcements.titlePlaceholder': { he: 'כותרת ההודעה...', en: 'Announcement title...' },
  'announcements.content': { he: 'תוכן', en: 'Content' },
  'announcements.contentPlaceholder': { he: 'תוכן ההודעה...', en: 'Write your announcement...' },
  'announcements.pinAnnouncement': { he: 'הצמדת הודעה', en: 'Pin Announcement' },
  'announcements.pinAnnouncementDesc': { he: 'הודעות מוצמדות מופיעות בראש הרשימה', en: 'Pinned announcements appear at the top of the list' },
  'announcements.publish': { he: 'פרסום הודעה', en: 'Publish' },
  'announcements.publishing': { he: 'בפרסום...', en: 'Publishing...' },
  'announcements.published': { he: 'ההודעה פורסמה!', en: 'Announcement published!' },
  'announcements.publishedDesc': { he: 'ההודעה גלויה כעת לכל המשתמשים.', en: 'Your announcement is now visible to all users.' },
  'announcements.deleteAnnouncement': { he: 'למחוק את ההודעה?', en: 'Delete announcement?' },
  'announcements.deleteAnnouncementDesc': { he: 'פעולה זו תמחק לצמיתות את ההודעה. לא ניתן לבטל פעולה זו.', en: 'This action will permanently delete the announcement. This cannot be undone.' },
  'announcements.deleted': { he: 'ההודעה נמחקה', en: 'Announcement deleted' },
  'announcements.deletedDesc': { he: 'ההודעה הוסרה.', en: 'The announcement has been removed.' },

  // Profile
  'profile.title': { he: 'פרופיל', en: 'Profile' },
  'profile.subtitle': { he: 'ניהול פרטי החשבון', en: 'Manage your account details' },
  'profile.personalInfo': { he: 'מידע אישי', en: 'Personal Information' },
  'profile.contactInfo': { he: 'פרטי התקשרות', en: 'Contact Information' },
  'profile.contactInfoDesc': { he: 'פרטי הקשר מנוהלים על ידי מנהלי המערכת', en: 'Contact details are managed by administrators' },
  'profile.about': { he: 'אודות', en: 'About' },
  'profile.aboutDesc': { he: 'קצת על עצמך', en: 'Tell others about yourself' },
  'profile.editProfile': { he: 'עריכת פרופיל', en: 'Edit Profile' },
  'profile.name': { he: 'שם מלא', en: 'Full Name' },
  'profile.namePlaceholder': { he: 'יש להזין שם מלא...', en: 'Enter your full name...' },
  'profile.bio': { he: 'ביוגרפיה', en: 'Biography' },
  'profile.bioPlaceholder': { he: 'ביוגרפיה קצרה על עצמך...', en: 'Write a short bio about yourself...' },
  'profile.noBio': { he: 'עדיין לא נוספה ביוגרפיה', en: 'No biography added yet' },
  'profile.socialLinks': { he: 'קישורים חברתיים', en: 'Social Links' },
  'profile.linkedinUrl': { he: 'כתובת LinkedIn', en: 'LinkedIn URL' },
  'profile.githubUrl': { he: 'כתובת GitHub', en: 'GitHub URL' },
  'profile.emailAddress': { he: 'כתובת אימייל', en: 'Email Address' },
  'profile.phoneNumber': { he: 'מספר טלפון', en: 'Phone Number' },
  'profile.noPhone': { he: 'לא סופק', en: 'Not provided' },
  'profile.contactAdmin': { he: 'לעדכון האימייל או מספר הטלפון, יש לפנות למנהל המערכת.', en: 'To update your email or phone number, please contact the administrator.' },
  'profile.memberSince': { he: 'תאריך הצטרפות', en: 'Joined' },
  'profile.saveChanges': { he: 'שמירת שינויים', en: 'Save Changes' },
  'profile.saving': { he: 'בשמירה...', en: 'Saving...' },
  'profile.saved': { he: 'הפרופיל עודכן', en: 'Profile updated' },
  'profile.savedDesc': { he: 'השינויים נשמרו בהצלחה.', en: 'Your changes have been saved successfully.' },
  'profile.avatarUpdated': { he: 'תמונת הפרופיל עודכנה', en: 'Profile picture updated' },
  'profile.avatarUpdatedDesc': { he: 'תמונת הפרופיל עודכנה בהצלחה.', en: 'Your profile picture has been updated successfully.' },
  'profile.avatarUploadError': { he: 'שגיאה בהעלאת התמונה', en: 'Error uploading image' },
  'profile.invalidImageType': { he: 'יש לבחור קובץ תמונה תקין', en: 'Please select a valid image file' },
  'profile.imageTooLarge': { he: 'הקובץ גדול מדי. הגודל המקסימלי הוא 5MB', en: 'File is too large. Maximum size is 5MB' },
  'profile.admin': { he: 'מנהל/ת', en: 'Admin' },
  'profile.instructor': { he: 'מרצה', en: 'Instructor' },
  'profile.student': { he: 'סטודנט/ית', en: 'Student' },
  'profile.changePassword': { he: 'שינוי סיסמה', en: 'Change Password' },
  'profile.changePasswordDesc': { he: 'עדכון סיסמת החשבון', en: 'Update your account password' },
  'profile.currentPassword': { he: 'סיסמה נוכחית', en: 'Current Password' },
  'profile.newPassword': { he: 'סיסמה חדשה', en: 'New Password' },
  'profile.confirmPassword': { he: 'אימות סיסמה', en: 'Confirm Password' },
  'profile.passwordMismatch': { he: 'הסיסמאות לא תואמות', en: 'Passwords do not match' },
  'profile.passwordMinLength': { he: 'הסיסמה חייבת להכיל לפחות 6 תווים', en: 'Password must be at least 6 characters' },
  'profile.passwordChanged': { he: 'הסיסמה עודכנה', en: 'Password changed' },
  'profile.passwordChangedDesc': { he: 'הסיסמה עודכנה בהצלחה.', en: 'Your password has been updated successfully.' },
  'profile.passwordChangeError': { he: 'שגיאה בעדכון הסיסמה', en: 'Error updating password' },
  'profile.changingPassword': { he: 'בעדכון סיסמה...', en: 'Changing password...' },

  // Admin
  'admin.manageUsers': { he: 'ניהול משתמשים', en: 'Manage Users' },
  'admin.manageUsersDesc': { he: 'הזמנה וניהול של חשבונות משתמשים', en: 'Invite and manage user accounts' },
  'admin.inviteUser': { he: 'הזמנת משתמש', en: 'Invite User' },
  'admin.inviteNewUser': { he: 'הזמנת משתמש חדש', en: 'Invite New User' },
  'admin.inviteNewUserDesc': { he: 'יצירת חשבון משתמש חדש ושליחת הזמנה', en: 'Create a new user account and send an invitation' },
  'admin.userEmail': { he: 'אימייל', en: 'Email' },
  'admin.userFullName': { he: 'שם מלא', en: 'Full Name' },
  'admin.selectRole': { he: 'תפקיד', en: 'Role' },
  'admin.tempPassword': { he: 'סיסמה זמנית (אופציונלי)', en: 'Temporary Password (optional)' },
  'admin.tempPasswordDesc': { he: 'יש להשאיר ריק ליצירת סיסמה מאובטחת אוטומטית', en: 'Leave empty to auto-generate a secure password' },
  'admin.student': { he: 'סטודנט/ית', en: 'Student' },
  'admin.instructor': { he: 'מרצה', en: 'Instructor' },
  'admin.admin': { he: 'מנהל/ת', en: 'Admin' },
  'admin.sendInvite': { he: 'שליחת הזמנה', en: 'Send Invite' },
  'admin.sending': { he: 'בשליחה...', en: 'Inviting...' },
  'admin.existingUsers': { he: 'כל המשתמשים', en: 'All Users' },
  'admin.noUsers': { he: 'לא נמצאו משתמשים', en: 'No users found' },
  'admin.changeRole': { he: 'שינוי תפקיד', en: 'Change Role' },
  'admin.searchUsers': { he: 'חיפוש משתמשים...', en: 'Search users...' },
  'admin.user': { he: 'משתמש/ת', en: 'User' },
  'admin.role': { he: 'תפקיד', en: 'Role' },
  'admin.joined': { he: 'הצטרפות', en: 'Joined' },
  'admin.actions': { he: 'פעולות', en: 'Actions' },
  'admin.setAsStudent': { he: 'הגדרה כסטודנט/ית', en: 'Set as Student' },
  'admin.setAsInstructor': { he: 'הגדרה כמרצה', en: 'Set as Instructor' },
  'admin.setAsAdmin': { he: 'הגדרה כמנהל/ת', en: 'Set as Admin' },
  'admin.userInvited': { he: 'המשתמש הוזמן!', en: 'User invited!' },
  'admin.roleUpdated': { he: 'התפקיד עודכן', en: 'Role updated' },
  'admin.roleUpdatedDesc': { he: 'תפקיד המשתמש עודכן בהצלחה.', en: 'The user role has been updated successfully.' },
  'admin.accessDenied': { he: 'הגישה נדחתה', en: 'Access Denied' },
  'admin.accessDeniedDesc': { he: 'אין הרשאה לגשת לעמוד זה.', en: 'You do not have permission to access this page.' },
  'admin.validEmail': { he: 'נא להזין אימייל תקין', en: 'Please enter a valid email' },
  'admin.nameMinLength': { he: 'השם חייב להכיל לפחות 2 תווים', en: 'Name must be at least 2 characters' },
  'admin.editUser': { he: 'עריכת משתמש', en: 'Edit User' },
  'admin.editUserDesc': { he: 'עדכון פרטי המשתמש', en: 'Update user details' },
  'admin.resetPassword': { he: 'איפוס סיסמה', en: 'Reset Password' },
  'admin.resetPasswordDesc': { he: 'הגדרת סיסמה חדשה למשתמש', en: 'Set a new password for user' },
  'admin.newPassword': { he: 'סיסמה חדשה', en: 'New Password' },
  'admin.passwordReset': { he: 'הסיסמה אופסה', en: 'Password Reset' },
  'admin.passwordResetDesc': { he: 'הסיסמה אופסה בהצלחה', en: 'Password has been reset successfully' },
  'admin.updateUser': { he: 'עדכון משתמש', en: 'Update User' },
  'admin.userUpdated': { he: 'המשתמש עודכן', en: 'User updated' },
  'admin.userUpdatedDesc': { he: 'פרטי המשתמש עודכנו בהצלחה', en: 'User details have been updated successfully' },
  'admin.resettingPassword': { he: 'באיפוס סיסמה...', en: 'Resetting password...' },
  'admin.deleteUser': { he: 'מחיקת משתמש', en: 'Delete User' },
  'admin.deleteUserConfirm': { he: 'האם למחוק את המשתמש?', en: 'Are you sure you want to delete this user?' },
  'admin.deleteUserConfirmDesc': { he: 'פעולה זו תמחק את כל נתוני המשתמש לצמיתות ולא ניתנת לביטול.', en: 'This action will permanently delete all user data and cannot be undone.' },
  'admin.userDeleted': { he: 'המשתמש נמחק', en: 'User Deleted' },
  'admin.userDeletedDesc': { he: 'המשתמש נמחק בהצלחה', en: 'User has been deleted successfully' },
  'admin.deletingUser': { he: 'במחיקה...', en: 'Deleting...' },
  'admin.activityHistory': { he: 'היסטוריית פעילות', en: 'Activity History' },
  'admin.activityHistoryDesc': { he: 'צפייה בפעילויות המשתמש', en: 'View user activities' },
  'admin.noActivities': { he: 'אין פעילויות עדיין', en: 'No activities yet' },
  'admin.activity.auth': { he: 'אימות', en: 'Authentication' },
  'admin.activity.login': { he: 'התחברות', en: 'Login' },
  'admin.activity.logout': { he: 'התנתקות', en: 'Logout' },
  'admin.activity.password_reset': { he: 'איפוס סיסמה', en: 'Password Reset' },
  'admin.activity.enrollment': { he: 'הרשמה לקורס', en: 'Course Enrollment' },
  'admin.activity.progress': { he: 'התקדמות בקורס', en: 'Course Progress' },
  'admin.activity.lesson': { he: 'שיעור', en: 'Lesson' },
  'admin.activity.exam': { he: 'מבחן', en: 'Exam' },
  'admin.activity.profile': { he: 'פרופיל', en: 'Profile' },
  'admin.activity.role': { he: 'תפקיד', en: 'Role' },
  'admin.activity.course_management': { he: 'ניהול קורסים', en: 'Course Management' },
  'admin.activity.course_enrolled': { he: 'הרשמה לקורס', en: 'Course Enrollment' },
  'admin.activity.lesson_completed': { he: 'השלמת שיעור', en: 'Lesson Completed' },
  'admin.activity.exam_completed': { he: 'השלמת מבחן', en: 'Exam Completed' },
  'admin.viewProgress': { he: 'צפייה בהתקדמות', en: 'View Progress' },
  'admin.studentProgress': { he: 'התקדמות התלמיד/ה', en: 'Student Progress' },
  'admin.enrolledCoursesList': { he: 'קורסים רשומים', en: 'Enrolled Courses' },
  'admin.noEnrollments': { he: 'אין רישום לאף קורס', en: 'Not enrolled in any courses' },
  'admin.enrolledAt': { he: 'נרשם/ה', en: 'Enrolled' },
  'admin.completed': { he: 'הושלם', en: 'Completed' },
  'admin.backToList': { he: 'חזרה לרשימה', en: 'Back to list' },

  // 404
  'notFound.title': { he: 'הדף לא נמצא', en: 'Page not found' },
  'notFound.subtitle': { he: 'אופס! הדף המבוקש לא קיים', en: 'Oops! The page you were looking for does not exist' },
  'notFound.backHome': { he: 'חזרה לדף הבית', en: 'Return to Home' },

  // Language
  'language.hebrew': { he: 'עברית', en: 'Hebrew' },
  'language.english': { he: 'אנגלית', en: 'English' },

  // Exam
  'exam.passed': { he: 'הצלחה!', en: 'You passed!' },
  'exam.failed': { he: 'המבחן לא עבר', en: 'You did not pass' },
  'exam.yourScore': { he: 'הציון שלך', en: 'Your score' },
  'exam.passingScore': { he: 'ציון עובר', en: 'Passing score' },
  'exam.submit': { he: 'הגשת מבחן', en: 'Submit Exam' },
  'exam.retryExam': { he: 'ניסיון נוסף', en: 'Try Again' },
  'exam.points': { he: 'נקודות', en: 'points' },
  'exam.multipleAnswers': { he: 'ניתן לבחור מספר תשובות', en: 'Select multiple answers' },
  'exam.explanation': { he: 'הסבר', en: 'Explanation' },
  'exam.notFound': { he: 'המבחן לא נמצא', en: 'Exam not found' },
  'exam.noQuestions': { he: 'אין שאלות במבחן זה', en: 'No questions in this exam' },
  'exam.noQuestionsDescription': { he: 'יש להוסיף שאלות דרך עמוד עריכת הקורס', en: 'Questions need to be added via the course edit page' },
  'exam.submitError': { he: 'שגיאה בהגשת המבחן', en: 'Error submitting exam' },
  'courseDetail.pdfPreviewUnavailable': { he: 'לא ניתן להציג תצוגה מקדימה של PDF', en: 'PDF preview unavailable' },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'he';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'he' ? 'rtl' : 'ltr';
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const translation = translations[key];
    if (!translation) {
      console.warn(`Missing translation for key: ${key}`);
      return key;
    }
    return translation[language];
  };

  const isRTL = language === 'he';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
