-- AI Learning Paths (Phase 5)
-- Stores adaptive learning paths generated by Aria for each user.

CREATE TABLE IF NOT EXISTS public.learning_paths (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  tenant_id uuid NOT NULL REFERENCES public.tenants(id) ON DELETE CASCADE,
  goal text NOT NULL,
  steps jsonb NOT NULL DEFAULT '[]'::jsonb,
  current_step int NOT NULL DEFAULT 0,
  generated_by text NOT NULL DEFAULT 'aria',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS learning_paths_user_tenant_idx
  ON public.learning_paths (user_id, tenant_id);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS learning_paths_updated_at ON public.learning_paths;
CREATE TRIGGER learning_paths_updated_at
  BEFORE UPDATE ON public.learning_paths
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- RLS
ALTER TABLE public.learning_paths ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "users_can_view_own_paths" ON public.learning_paths;
CREATE POLICY "users_can_view_own_paths"
  ON public.learning_paths FOR SELECT
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "users_can_insert_own_paths" ON public.learning_paths;
CREATE POLICY "users_can_insert_own_paths"
  ON public.learning_paths FOR INSERT
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "users_can_update_own_paths" ON public.learning_paths;
CREATE POLICY "users_can_update_own_paths"
  ON public.learning_paths FOR UPDATE
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "users_can_delete_own_paths" ON public.learning_paths;
CREATE POLICY "users_can_delete_own_paths"
  ON public.learning_paths FOR DELETE
  USING (auth.uid() = user_id);

COMMENT ON TABLE public.learning_paths IS 'AI-generated adaptive learning paths per user (Phase 5)';
COMMENT ON COLUMN public.learning_paths.goal IS 'User-stated goal in natural language (Hebrew or English)';
COMMENT ON COLUMN public.learning_paths.steps IS 'Ordered list of {course_id, course_title, reason} objects';
COMMENT ON COLUMN public.learning_paths.current_step IS 'Index of the current step the user is on';
