// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { demoSupabase, DEMO_USER } from './demoClient';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const DEMO_MODE = import.meta.env.VITE_DEMO_MODE === 'true';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = DEMO_MODE
  ? demoSupabase
  : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    });

if (DEMO_MODE && typeof window !== 'undefined') {
  // eslint-disable-next-line no-console
  console.info(
    `%c[DEMO MODE]%c Logged-in client is mocked. Sign in with ${DEMO_USER.email} / ${DEMO_USER.password}`,
    'background:#7c3aed;color:white;padding:2px 6px;border-radius:4px;font-weight:bold',
    'color:inherit'
  );
}